<?php

namespace Frontend\AppBundle\Entity;

use \DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
       public function filterCategories($filtro){
        
        $searchtext = $filtro['searchtextcat'];   
        
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
        
        if(isset($searchtext) && $searchtext != '' ){
        $qb->andWhere('c.name like :searchtext');
        $qb->setParameter('searchtext', '%'.$searchtext.'%');
        }
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        }
        
    
}
