<?php

namespace Frontend\AppBundle\Entity;

use \DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * ContactInvestorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactInvestorRepository extends EntityRepository
{
       public function filterContacts($filtro){
        
        //$status = $filtro['status'];
        $searchtext = $filtro['searchtextcontacts'];   
           
        $actual = new DateTime();
        $now = date_format($actual, 'Y-m-d');        
        
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
        //$qb->join('n.status', 's');
        
        if(isset($searchtext) && $searchtext != '' ){
        $qb->andWhere('c.text like :searchtext OR c.email like :searchtext');
        $qb->setParameter('searchtext', '%'.$searchtext.'%');
        }
        
       /* if(isset($status) && $status != ''){
        $qb->andWhere('s.id = :status');
        $qb->setParameter('status', $status);
        }*/
        $qb->orderBy('c.dateCreated','DESC');
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
        
        
        
        
    
    
}
