<?php

namespace Frontend\AppBundle\Entity;

use \DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * ContactOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactOwnerRepository extends EntityRepository
{
       public function filterContacts($filtro){
        
        $status = $filtro['status'];
        $searchtext = $filtro['searchtextcontacts'];   
        $reply = $filtro['reply'];   
        
        $actual = new DateTime();
        $now = date_format($actual, 'Y-m-d');        
        
        $qb = $this->createQueryBuilder('c');
        $qb->select('c, u, s');
        $qb->join('c.user', 'u');
        $qb->join('c.status', 's');    
        
        if(isset($searchtext) && $searchtext != '' ){
        $qb->andWhere('c.text like :searchtext OR u.email like :searchtext OR c.serie like :searchtext');
        $qb->setParameter('searchtext', '%'.$searchtext.'%');
        }
        
        if(isset($status) && $status != ''){
        
        $qb->andWhere('s.id = :status');
        $qb->setParameter('status', $status);
        }
        
        if(isset($reply) && $reply != ''){
        $qb->andWhere('c.replied = :reply');
        $qb->setParameter('reply', $reply);
        }
        
        $qb->orderBy('c.dateCreated','DESC');
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
        
        
        
        
    
    
}
