<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \DateTime;

/**
 * MakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakeRepository extends EntityRepository
{
    public function selectDistinctMakes()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->select('m.makeId');
        $qb->orderBy('m.makeId', "ASC");
        $qb->distinct(true);
        $query = $qb->getQuery();
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
