<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \DateTime;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends EntityRepository
{
    public function selectDistinctModels($makesIds)
    {
        if ($makesIds->count() > 0) {
            $qb = $this->createQueryBuilder('m');
            $qb->select('m.modelId');
          //  $qb->select('m.id');

            $counter = 1;
            foreach ($makesIds as $id) {
                $qb->orWhere('m.make = :make' . $counter);
                $qb->setParameter('make' . $counter, $id);
                $counter++;
            }

            $qb->distinct(true);
            $query = $qb->getQuery();
            try {
                return $query->getResult();
            } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
            }
        } else {
            return null;
        }
    }
}
