<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \DateTime;

/**
 * ProfileImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileImageRepository extends EntityRepository
{
        
           
         public function getImagesInOrder($gallery_id){
        
        $qb = $this->createQueryBuilder('i');
        $qb->select('i');
        $qb->join('i.gallery', ':gallery');
        $qb->orderBy('i.orden','ASC');
        $qb->setParameter('gallery', $gallery_id);
        $query = $qb->getQuery();
       
       
        
        
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
    
    
}
