<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRateRepository extends EntityRepository
{
       public function getPropertyRate($property){
        
        $qb = $this->createQueryBuilder('r');
        $qb->select('r, p');
        $qb->join('r.property', 'p');
        $qb->andWhere('p.id = :id');
        $qb->setParameter('id', $property);
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
        
        
        
        
    
    
}
