<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
     public function getReviewsByPropertyAndStatus($property, $status){
        
        $qb = $this->createQueryBuilder('r');
        $qb->select('r');
        $qb->andWhere('r.status = :id');
        $qb->andWhere('r.property = :pid');
        $qb->setParameter('id', $status)->setParameter('pid', $property);
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
        
        
        
           public function getLastReviewsByUser($user, $cant, $status){
        
        $qb = $this->createQueryBuilder('r');
        $qb->select('r, u, p, s');
        $qb->join('r.property', 'p');
        $qb->join('p.user', 'u');
        $qb->join('p.status', 's');
        $qb->andWhere('p.user = :user');
        $qb->andWhere('s.id = :status');
        $qb->andWhere('r.status = :status');
        $qb->setMaxResults($cant);
        $qb->orderBy('r.dateCreated','DESC');
        $qb->setParameter('user', $user);
        $qb->setParameter('status', $status);
        $query = $qb->getQuery();
       
       
        
        
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
        
        
         public function filterSuperAdminReviews($filtro){
        
            
            
        $status = $filtro['status'];
        $searchtext = $filtro['searchtext'];
        
        
        $qb = $this->createQueryBuilder('r');
        $qb->select('r,  p');
        $qb->join('r.property', 'p');
        $qb->join('r.status', 's');
        
        if(isset($searchtext) && $searchtext != ''){
        $qb->andWhere('r.guest = :searchtext OR p.serie = :searchtext OR r.email = :searchtext');
        $qb->setParameter('searchtext', $searchtext);
        }
        
         if(isset($status) && $status != ''){
        $qb->andWhere('s.id = :status');
        $qb->setParameter('status', $status);
        }
     
        $qb->orderBy('r.dateCreated','DESC');
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
       
        
    
    
}
