<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchControlRepository extends EntityRepository {

    public function findSearch($country = null, $region = null, $city = null) {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s');
        if ($country != null && $country != '') {
            $qb->andWhere('s.countrySlug = :country');
            $qb->setParameter('country', $country);
        }else {
            $country = '';
            $qb->andWhere('s.countrySlug = :country');
            $qb->setParameter('country', $country);
        }
        if ($region != null && $region != '') {
            $qb->andWhere('s.stateProvinceSlug = :region');
            $qb->setParameter('region', $region);
        }else {
            $region = '';
            $qb->andWhere('s.stateProvinceSlug = :region');
            $qb->setParameter('region', $region);
        }

        if ($city != null && $city != '') {
            $qb->andWhere('s.localitySlug = :city');
            $qb->setParameter('city', $city);
        }else {
            $city = '';
            $qb->andWhere('s.localitySlug = :city');
            $qb->setParameter('city', $city);
        }


        $query = $qb->getQuery();

        try {
            return $query->getOneOrNullResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
