<?php

namespace Frontend\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \DateTime;

/**
 * TrimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrimRepository extends EntityRepository
{
    public function selectDistinctTrims($modelsIds)
    {
        if ($modelsIds->count() > 0) {
            $qb = $this->createQueryBuilder('m');
            $qb->select('m.trimId');
            //  $qb->select('m.id');

            $counter = 1;
            foreach ($modelsIds as $id) {
                $qb->orWhere('m.model = :model' . $counter);
                $qb->setParameter('model' . $counter, $id);
                $counter++;
            }

            $qb->distinct(true);
            $query = $qb->getQuery();
            try {
                return $query->getResult();
            } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
            }
        } else {
            return null;
        }
    }
}
