<?php

namespace Frontend\AppBundle\Entity;

use \DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
       public function filterUsers($filtro){
        
        $status = $filtro['status'];
        $searchtext = $filtro['searchtextuser'];   
           
        $actual = new DateTime();
        $now = date_format($actual, 'Y-m-d');        
        
        $qb = $this->createQueryBuilder('u');
        $qb->select('u');
        
        
        
        if(isset($searchtext) && $searchtext != '' ){
        $qb->andWhere('u.email like :searchtext OR u.name like :searchtext');
        $qb->setParameter('searchtext', '%'.$searchtext.'%');
        }
        
       if(isset($status) && $status != ''){
        $qb->andWhere('u.enabled = :status');
        $qb->setParameter('status', $status);
        }
        $qb->orderBy('u.dateCreated','DESC');
        
        $qb->andWhere('u.roles = :roles');
        $qb->setParameter('roles', 'a:0:{}');
        
        $query = $qb->getQuery();
       
        try {
        return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
        }
        
        }
        
        
        
        
    
    
}
