parameters:
#    private_seller.example.class: Backend\PrivateSellerBundle\Example

services:
#    private_seller.example:
#        class: %private_seller.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
