parameters:
#    super_admin.example.class: Backend\SuperAdminBundle\Example

services:
#    super_admin.example:
#        class: %super_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
