parameters:
#    shopper.example.class: Backend\ShopperBundle\Example

services:
#    shopper.example:
#        class: %shopper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
