Frontend\AppBundle\Entity\PropertyDetails:
    properties:
        size:
          - NotBlank:
              message: "fill out this field"
              groups: [propertyDetails]
          - Length:
              min: 1
              max: 7
              minMessage: "Size must have {{ limit }} characters at least"
              maxMessage: "Size must have  {{ limit }} characters or less"
              groups: [propertyDetails]
          - Regex:
              pattern: "/^[0-9]{1,7}$/"
              match:   true
              message: Invalid Size
              groups: [propertyDetails]     
              
Frontend\AppBundle\Entity\OtherPaymentsOptions:
    properties:
        maximumStay:
          - NotBlank:
              message: "fill out this field"
              groups: [otherPayments]
          - Length:
              min: 1
              max: 3
              minMessage: "Invalid field {{ limit }} characters at least"
              maxMessage: "Invalid field {{ limit }} characters or less"
              groups: [otherPayments]
          - Regex:
              pattern: "/^[0-9]{1,3}$/"
              match:   true
              message: Invalid Size
              groups: [otherPayments]   
              
Frontend\AppBundle\Entity\Period:
    properties:
        minStay:
          - NotBlank:
              message: "fill out this field"
              groups: [propertyPeriod]
          - Length:
              min: 1
              max: 255
              minMessage: "Invalid field {{ limit }} characters at least"
              maxMessage: "Invalid field {{ limit }} characters or less"
              groups: [propertyPeriod]
        nightly:
          - NotBlank:
              message: "fill out this field"
              groups: [propertyPeriod]
          - Range:
                min: 1
                max: 9999999
                minMessage: Invalid minimun price, {{ limit }} at least
                maxMessage: Price cannot be greater than {{ limit }}
        weekly:
          - NotBlank:
              message: "fill out this field"
              groups: [propertyPeriod]
          - Range:
                min: 1
                max: 9999999
                minMessage: Invalid minimun price, {{ limit }} at least
                maxMessage: Price cannot be greater than {{ limit }}  
        monthly:
          - NotBlank:
              message: "fill out this field"
              groups: [propertyPeriod]
          - Range:
                min: 1
                max: 9999999
                minMessage: Invalid minimun price, {{ limit }} at least
                maxMessage: Price cannot be greater than {{ limit }}
              
Frontend\AppBundle\Entity\PropertyImage:
    properties:
        photo:
          - File:
              maxSize: 44k
              mimeTypes: [image/jpeg, image/gif, image/png, image/tiff]
              mimeTypesMessage: Please upload a valid Image 
              groups: [propertyImage]