<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VehicleBasicInformation extends \Frontend\AppBundle\Entity\VehicleBasicInformation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'zipcode', 'msrp', 'vin', 'year', 'condition', 'model', 'make', 'bodyStyle', 'price', 'mileage', 'stock_number');
        }

        return array('__isInitialized__', 'id', 'zipcode', 'msrp', 'vin', 'year', 'condition', 'model', 'make', 'bodyStyle', 'price', 'mileage', 'stock_number');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VehicleBasicInformation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCondition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondition', array());

        return parent::getCondition();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondition(\Frontend\AppBundle\Entity\Condition $condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondition', array($condition));

        return parent::setCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockNumber', array());

        return parent::getStockNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockNumber($stock_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockNumber', array($stock_number));

        return parent::setStockNumber($stock_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', array());

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear(\Frontend\AppBundle\Entity\Year $year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', array($year));

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getMake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMake', array());

        return parent::getMake();
    }

    /**
     * {@inheritDoc}
     */
    public function setMake(\Frontend\AppBundle\Entity\Make $make)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMake', array($make));

        return parent::setMake($make);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', array());

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(\Frontend\AppBundle\Entity\Model $model)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', array($model));

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsrp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsrp', array());

        return parent::getMsrp();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsrp($msrp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsrp', array($msrp));

        return parent::setMsrp($msrp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setMileage($mileage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMileage', array($mileage));

        return parent::setMileage($mileage);
    }

    /**
     * {@inheritDoc}
     */
    public function getMileage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMileage', array());

        return parent::getMileage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVin($vin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVin', array($vin));

        return parent::setVin($vin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVin', array());

        return parent::getVin();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getBodyStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBodyStyle', array());

        return parent::getBodyStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBodyStyle($bodyStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBodyStyle', array($bodyStyle));

        return parent::setBodyStyle($bodyStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipcode', array());

        return parent::getZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipcode($zipcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipcode', array($zipcode));

        return parent::setZipcode($zipcode);
    }

}
