<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ElectronicsEntertaimentAmenities extends \Frontend\AppBundle\Entity\ElectronicsEntertaimentAmenities implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'cableTv', 'dialUpInternetAccess', 'dvdLibrary', 'homeStereo', 'premiunChannels', 'tv', 'tvGames', 'vcrPlayer', 'wirelessInternetAccess');
        }

        return array('__isInitialized__', 'id', 'cableTv', 'dialUpInternetAccess', 'dvdLibrary', 'homeStereo', 'premiunChannels', 'tv', 'tvGames', 'vcrPlayer', 'wirelessInternetAccess');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ElectronicsEntertaimentAmenities $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCableTv($cableTv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCableTv', array($cableTv));

        return parent::setCableTv($cableTv);
    }

    /**
     * {@inheritDoc}
     */
    public function getCableTv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCableTv', array());

        return parent::getCableTv();
    }

    /**
     * {@inheritDoc}
     */
    public function setDialUpInternetAccess($dialUpInternetAccess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDialUpInternetAccess', array($dialUpInternetAccess));

        return parent::setDialUpInternetAccess($dialUpInternetAccess);
    }

    /**
     * {@inheritDoc}
     */
    public function getDialUpInternetAccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDialUpInternetAccess', array());

        return parent::getDialUpInternetAccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setDvdLibrary($dvdLibrary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDvdLibrary', array($dvdLibrary));

        return parent::setDvdLibrary($dvdLibrary);
    }

    /**
     * {@inheritDoc}
     */
    public function getDvdLibrary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDvdLibrary', array());

        return parent::getDvdLibrary();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomeStereo($homeStereo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomeStereo', array($homeStereo));

        return parent::setHomeStereo($homeStereo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomeStereo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomeStereo', array());

        return parent::getHomeStereo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremiunChannels($premiunChannels)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremiunChannels', array($premiunChannels));

        return parent::setPremiunChannels($premiunChannels);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremiunChannels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremiunChannels', array());

        return parent::getPremiunChannels();
    }

    /**
     * {@inheritDoc}
     */
    public function setTv($tv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTv', array($tv));

        return parent::setTv($tv);
    }

    /**
     * {@inheritDoc}
     */
    public function getTv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTv', array());

        return parent::getTv();
    }

    /**
     * {@inheritDoc}
     */
    public function setTvGames($tvGames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvGames', array($tvGames));

        return parent::setTvGames($tvGames);
    }

    /**
     * {@inheritDoc}
     */
    public function getTvGames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvGames', array());

        return parent::getTvGames();
    }

    /**
     * {@inheritDoc}
     */
    public function setVcrPlayer($vcrPlayer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVcrPlayer', array($vcrPlayer));

        return parent::setVcrPlayer($vcrPlayer);
    }

    /**
     * {@inheritDoc}
     */
    public function getVcrPlayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVcrPlayer', array());

        return parent::getVcrPlayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setWirelessInternetAccess($wirelessInternetAccess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWirelessInternetAccess', array($wirelessInternetAccess));

        return parent::setWirelessInternetAccess($wirelessInternetAccess);
    }

    /**
     * {@inheritDoc}
     */
    public function getWirelessInternetAccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWirelessInternetAccess', array());

        return parent::getWirelessInternetAccess();
    }

}
