<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \Frontend\AppBundle\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'displayName', 'email', 'displayEmail', 'phone1', 'displayPhone1', 'phone2', 'displayPhone2', 'phone3', 'displayPhone3', 'fax', 'displayFax', 'webPage', 'displayWebPage', 'languages', 'contactType', 'countryphonecode');
        }

        return array('__isInitialized__', 'id', 'name', 'displayName', 'email', 'displayEmail', 'phone1', 'displayPhone1', 'phone2', 'displayPhone2', 'phone3', 'displayPhone3', 'fax', 'displayFax', 'webPage', 'displayWebPage', 'languages', 'contactType', 'countryphonecode');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryPhoneCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryPhoneCode', array());

        return parent::getCountryPhoneCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryPhoneCode($countryphonecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryPhoneCode', array($countryphonecode));

        return parent::setCountryPhoneCode($countryphonecode);
    }

    /**
     * {@inheritDoc}
     */
    public function setContactType($contactType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactType', array($contactType));

        return parent::setContactType($contactType);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactType', array());

        return parent::getContactType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', array($displayName));

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayEmail($displayEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayEmail', array($displayEmail));

        return parent::setDisplayEmail($displayEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayEmail', array());

        return parent::getDisplayEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone1($phone1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone1', array($phone1));

        return parent::setPhone1($phone1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone1', array());

        return parent::getPhone1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayPhone1($displayPhone1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayPhone1', array($displayPhone1));

        return parent::setDisplayPhone1($displayPhone1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayPhone1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayPhone1', array());

        return parent::getDisplayPhone1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone2($phone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone2', array($phone2));

        return parent::setPhone2($phone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone2', array());

        return parent::getPhone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayPhone2($displayPhone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayPhone2', array($displayPhone2));

        return parent::setDisplayPhone2($displayPhone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayPhone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayPhone2', array());

        return parent::getDisplayPhone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone3($phone3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone3', array($phone3));

        return parent::setPhone3($phone3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone3', array());

        return parent::getPhone3();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayPhone3($displayPhone3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayPhone3', array($displayPhone3));

        return parent::setDisplayPhone3($displayPhone3);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayPhone3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayPhone3', array());

        return parent::getDisplayPhone3();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayFax($displayFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayFax', array($displayFax));

        return parent::setDisplayFax($displayFax);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayFax', array());

        return parent::getDisplayFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebPage($WebPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebPage', array($WebPage));

        return parent::setWebPage($WebPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPage', array());

        return parent::getWebPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayWebPage($displayWebPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayWebPage', array($displayWebPage));

        return parent::setDisplayWebPage($displayWebPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayWebPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayWebPage', array());

        return parent::getDisplayWebPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguages($languages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguages', array($languages));

        return parent::setLanguages($languages);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguages', array());

        return parent::getLanguages();
    }

}
