<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HomeAmenities extends \Frontend\AppBundle\Entity\HomeAmenities implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'airConditioned', 'balcony', 'ceilingFans', 'petsAllowed', 'communityExerciseRoom', 'fullkitchen', 'garage', 'longTermRenters', 'heater', 'nonSmokingOnly', 'pool', 'childrenWelcome', 'telephone', 'fireplace', 'hotTub', 'washingMachine', 'parking', 'wheelchairAccessible');
        }

        return array('__isInitialized__', 'id', 'airConditioned', 'balcony', 'ceilingFans', 'petsAllowed', 'communityExerciseRoom', 'fullkitchen', 'garage', 'longTermRenters', 'heater', 'nonSmokingOnly', 'pool', 'childrenWelcome', 'telephone', 'fireplace', 'hotTub', 'washingMachine', 'parking', 'wheelchairAccessible');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HomeAmenities $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirConditioned($airConditioned)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirConditioned', array($airConditioned));

        return parent::setAirConditioned($airConditioned);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirConditioned()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirConditioned', array());

        return parent::getAirConditioned();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalcony($balcony)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalcony', array($balcony));

        return parent::setBalcony($balcony);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalcony()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalcony', array());

        return parent::getBalcony();
    }

    /**
     * {@inheritDoc}
     */
    public function setCeilingFans($ceilingFans)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCeilingFans', array($ceilingFans));

        return parent::setCeilingFans($ceilingFans);
    }

    /**
     * {@inheritDoc}
     */
    public function getCeilingFans()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCeilingFans', array());

        return parent::getCeilingFans();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetsAllowed($petsAllowed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetsAllowed', array($petsAllowed));

        return parent::setPetsAllowed($petsAllowed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetsAllowed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetsAllowed', array());

        return parent::getPetsAllowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommunityExerciseRoom($communityExerciseRoom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommunityExerciseRoom', array($communityExerciseRoom));

        return parent::setCommunityExerciseRoom($communityExerciseRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommunityExerciseRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommunityExerciseRoom', array());

        return parent::getCommunityExerciseRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullkitchen($fullkitchen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullkitchen', array($fullkitchen));

        return parent::setFullkitchen($fullkitchen);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullkitchen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullkitchen', array());

        return parent::getFullkitchen();
    }

    /**
     * {@inheritDoc}
     */
    public function setGarage($garage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGarage', array($garage));

        return parent::setGarage($garage);
    }

    /**
     * {@inheritDoc}
     */
    public function getGarage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGarage', array());

        return parent::getGarage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongTermRenters($longTermRenters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongTermRenters', array($longTermRenters));

        return parent::setLongTermRenters($longTermRenters);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongTermRenters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongTermRenters', array());

        return parent::getLongTermRenters();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeater($heater)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeater', array($heater));

        return parent::setHeater($heater);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeater()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeater', array());

        return parent::getHeater();
    }

    /**
     * {@inheritDoc}
     */
    public function setNonSmokingOnly($nonSmokingOnly)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNonSmokingOnly', array($nonSmokingOnly));

        return parent::setNonSmokingOnly($nonSmokingOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function getNonSmokingOnly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNonSmokingOnly', array());

        return parent::getNonSmokingOnly();
    }

    /**
     * {@inheritDoc}
     */
    public function setPool($pool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPool', array($pool));

        return parent::setPool($pool);
    }

    /**
     * {@inheritDoc}
     */
    public function getPool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPool', array());

        return parent::getPool();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildrenWelcome($childrenWelcome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildrenWelcome', array($childrenWelcome));

        return parent::setChildrenWelcome($childrenWelcome);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildrenWelcome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildrenWelcome', array());

        return parent::getChildrenWelcome();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setFireplace($fireplace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFireplace', array($fireplace));

        return parent::setFireplace($fireplace);
    }

    /**
     * {@inheritDoc}
     */
    public function getFireplace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFireplace', array());

        return parent::getFireplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotTub($hotTub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotTub', array($hotTub));

        return parent::setHotTub($hotTub);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotTub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotTub', array());

        return parent::getHotTub();
    }

    /**
     * {@inheritDoc}
     */
    public function setWashingMachine($washingMachine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWashingMachine', array($washingMachine));

        return parent::setWashingMachine($washingMachine);
    }

    /**
     * {@inheritDoc}
     */
    public function getWashingMachine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWashingMachine', array());

        return parent::getWashingMachine();
    }

    /**
     * {@inheritDoc}
     */
    public function setParking($parking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParking', array($parking));

        return parent::setParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function getParking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParking', array());

        return parent::getParking();
    }

    /**
     * {@inheritDoc}
     */
    public function setWheelchairAccessible($wheelchairAccessible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWheelchairAccessible', array($wheelchairAccessible));

        return parent::setWheelchairAccessible($wheelchairAccessible);
    }

    /**
     * {@inheritDoc}
     */
    public function getWheelchairAccessible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWheelchairAccessible', array());

        return parent::getWheelchairAccessible();
    }

}
