<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaymentsOptions extends \Frontend\AppBundle\Entity\PaymentsOptions implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'americanExpress', 'wireTransfer', 'mastercard', 'cashiersCheck', 'visa', 'moneyOrder', 'discover', 'paypal', 'onlinePayment');
        }

        return array('__isInitialized__', 'id', 'americanExpress', 'wireTransfer', 'mastercard', 'cashiersCheck', 'visa', 'moneyOrder', 'discover', 'paypal', 'onlinePayment');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaymentsOptions $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmericanExpress($americanExpress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmericanExpress', array($americanExpress));

        return parent::setAmericanExpress($americanExpress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmericanExpress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmericanExpress', array());

        return parent::getAmericanExpress();
    }

    /**
     * {@inheritDoc}
     */
    public function setWireTransfer($wireTransfer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWireTransfer', array($wireTransfer));

        return parent::setWireTransfer($wireTransfer);
    }

    /**
     * {@inheritDoc}
     */
    public function getWireTransfer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWireTransfer', array());

        return parent::getWireTransfer();
    }

    /**
     * {@inheritDoc}
     */
    public function setMastercard($mastercard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMastercard', array($mastercard));

        return parent::setMastercard($mastercard);
    }

    /**
     * {@inheritDoc}
     */
    public function getMastercard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMastercard', array());

        return parent::getMastercard();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashiersCheck($cashiersCheck)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashiersCheck', array($cashiersCheck));

        return parent::setCashiersCheck($cashiersCheck);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashiersCheck()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashiersCheck', array());

        return parent::getCashiersCheck();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisa($visa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisa', array($visa));

        return parent::setVisa($visa);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisa', array());

        return parent::getVisa();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyOrder($moneyOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyOrder', array($moneyOrder));

        return parent::setMoneyOrder($moneyOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyOrder', array());

        return parent::getMoneyOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscover($discover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscover', array($discover));

        return parent::setDiscover($discover);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscover', array());

        return parent::getDiscover();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaypal($paypal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaypal', array($paypal));

        return parent::setPaypal($paypal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaypal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaypal', array());

        return parent::getPaypal();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnlinePayment($onlinePayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnlinePayment', array($onlinePayment));

        return parent::setOnlinePayment($onlinePayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnlinePayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnlinePayment', array());

        return parent::getOnlinePayment();
    }

}
