<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \Frontend\AppBundle\Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'location', 'gallery', 'description', 'contact', 'user', 'status', 'reviews', 'dateCreated', 'dateUpdate', 'views', 'full', 'rating', 'serie', 'featured', 'file_name', 'photo', 'path', 'logo', 'children', 'parent', 'profileservices', 'services', 'feeds', 'vehicles', 'usefulinformation', 'emails', 'inventory');
        }

        return array('__isInitialized__', 'id', 'location', 'gallery', 'description', 'contact', 'user', 'status', 'reviews', 'dateCreated', 'dateUpdate', 'views', 'full', 'rating', 'serie', 'featured', 'file_name', 'photo', 'path', 'logo', 'children', 'parent', 'profileservices', 'services', 'feeds', 'vehicles', 'usefulinformation', 'emails', 'inventory');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDateUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdate', array());

        return parent::getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdate($dateUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdate', array($dateUpdate));

        return parent::setDateUpdate($dateUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($logo));

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsefulinformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsefulinformation', array());

        return parent::getUsefulinformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsefulinformation($usefulinformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsefulinformation', array($usefulinformation));

        return parent::setUsefulinformation($usefulinformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServices', array());

        return parent::getServices();
    }

    /**
     * {@inheritDoc}
     */
    public function setServices($services)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServices', array($services));

        return parent::setServices($services);
    }

    /**
     * {@inheritDoc}
     */
    public function HasService($profileServices, $service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'HasService', array($profileServices, $service));

        return parent::HasService($profileServices, $service);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehicles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehicles', array());

        return parent::getVehicles();
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiclesComplete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiclesComplete', array());

        return parent::getVehiclesComplete();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfileVehicles(\Frontend\AppBundle\Entity\Vehicle $vehicle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfileVehicles', array($vehicle));

        return parent::addProfileVehicles($vehicle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmails', array());

        return parent::getEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfileEmails(\Frontend\AppBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfileEmails', array($email));

        return parent::addProfileEmails($email);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfileEmails(\Frontend\AppBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfileEmails', array($email));

        return parent::removeProfileEmails($email);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfileVehicles(\Frontend\AppBundle\Entity\Vehicle $vehicle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfileVehicles', array($vehicle));

        return parent::removeProfileVehicles($vehicle);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileServices', array());

        return parent::getProfileServices();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileServices(\Frontend\AppBundle\Entity\ProfileServices $profileservices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileServices', array($profileservices));

        return parent::setProfileServices($profileservices);
    }

    /**
     * {@inheritDoc}
     */
    public function addProfileServices(\Frontend\AppBundle\Entity\ProfileServices $profileservices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfileServices', array($profileservices));

        return parent::addProfileServices($profileservices);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfileServices(\Frontend\AppBundle\Entity\ProfileServices $profileservices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfileServices', array($profileservices));

        return parent::removeProfileServices($profileservices);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeeds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeeds', array());

        return parent::getFeeds();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeeds(\Frontend\AppBundle\Entity\Feeds $feeds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeeds', array($feeds));

        return parent::setFeeds($feeds);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\Frontend\AppBundle\Entity\Location $location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', array($location));

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', array());

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setGallery(\Frontend\AppBundle\Entity\Gallery $gallery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGallery', array($gallery));

        return parent::setGallery($gallery);
    }

    /**
     * {@inheritDoc}
     */
    public function getGallery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGallery', array());

        return parent::getGallery();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Frontend\AppBundle\Entity\Profile $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(\Frontend\AppBundle\Entity\Description $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(\Frontend\AppBundle\Entity\Contact $contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Frontend\AppBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\Frontend\AppBundle\Entity\Status $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getReviews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', array());

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfileReviews(\Frontend\AppBundle\Entity\Review $review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfileReviews', array($review));

        return parent::addProfileReviews($review);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfileReviews(\Frontend\AppBundle\Entity\Review $review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfileReviews', array($review));

        return parent::removeProfileReviews($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsByStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsByStatus', array($status));

        return parent::getReviewsByStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getInquiries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInquiries', array());

        return parent::getInquiries();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewInquiries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewInquiries', array());

        return parent::getNewInquiries();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewReviews($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewReviews', array($status));

        return parent::getNewReviews($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setFull($full)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFull', array($full));

        return parent::setFull($full);
    }

    /**
     * {@inheritDoc}
     */
    public function getFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFull', array());

        return parent::getFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setViews($views)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViews', array($views));

        return parent::setViews($views);
    }

    /**
     * {@inheritDoc}
     */
    public function getViews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViews', array());

        return parent::getViews();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating(\Frontend\AppBundle\Entity\ProfileRate $rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', array($rating));

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', array());

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerie($serie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerie', array($serie));

        return parent::setSerie($serie);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerie', array());

        return parent::getSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatured($featured)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatured', array($featured));

        return parent::setFeatured($featured);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatured', array());

        return parent::getFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileName($fileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileName', array($fileName));

        return parent::setFileName($fileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileName', array());

        return parent::getFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(\Symfony\Component\HttpFoundation\File\UploadedFile $photo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', array());

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function upload($dir, $ipath, $iiid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array($dir, $ipath, $iiid));

        return parent::upload($dir, $ipath, $iiid);
    }

    /**
     * {@inheritDoc}
     */
    public function __tostring()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__tostring', array());

        return parent::__tostring();
    }

    /**
     * {@inheritDoc}
     */
    public function FindServiceByServiceId($serv_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'FindServiceByServiceId', array($serv_id));

        return parent::FindServiceByServiceId($serv_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getInventory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventory', array());

        return parent::getInventory();
    }

}
