<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PlacesActivities extends \Frontend\AppBundle\Entity\PlacesActivities implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'car', 'nearestAirport', 'nearestAirportDistance', 'nearestAirportDistanceUnit', 'nearestBeach', 'nearestBeachDistance', 'nearestBeachDistanceUnit', 'nearestFerry', 'nearestFerryDistance', 'nearestFerryDistanceUnit', 'nearestTrain', 'nearestTrainDistance', 'nearestTrainDistanceUnit', 'nearestHighway', 'nearestHighwayDistance', 'nearestHighwayDistanceUnit', 'nearestBar', 'nearestBarDistance', 'nearestBarDistanceUnit', 'nearestSki', 'nearestSkiDistance', 'nearestSkiDistanceUnit', 'nearestGolf', 'nearestGolfDistance', 'nearestGolfDistanceUnit', 'nearestRestaurant', 'nearestRestaurantDistance', 'nearestRestaurantDistanceUnit');
        }

        return array('__isInitialized__', 'id', 'car', 'nearestAirport', 'nearestAirportDistance', 'nearestAirportDistanceUnit', 'nearestBeach', 'nearestBeachDistance', 'nearestBeachDistanceUnit', 'nearestFerry', 'nearestFerryDistance', 'nearestFerryDistanceUnit', 'nearestTrain', 'nearestTrainDistance', 'nearestTrainDistanceUnit', 'nearestHighway', 'nearestHighwayDistance', 'nearestHighwayDistanceUnit', 'nearestBar', 'nearestBarDistance', 'nearestBarDistanceUnit', 'nearestSki', 'nearestSkiDistance', 'nearestSkiDistanceUnit', 'nearestGolf', 'nearestGolfDistance', 'nearestGolfDistanceUnit', 'nearestRestaurant', 'nearestRestaurantDistance', 'nearestRestaurantDistanceUnit');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PlacesActivities $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCar($car)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCar', array($car));

        return parent::setCar($car);
    }

    /**
     * {@inheritDoc}
     */
    public function getCar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCar', array());

        return parent::getCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestAirport($nearestAirport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestAirport', array($nearestAirport));

        return parent::setNearestAirport($nearestAirport);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestAirport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestAirport', array());

        return parent::getNearestAirport();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestAirportDistance($nearestAirportDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestAirportDistance', array($nearestAirportDistance));

        return parent::setNearestAirportDistance($nearestAirportDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestAirportDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestAirportDistance', array());

        return parent::getNearestAirportDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestAirportDistanceUnit($nearestAirportDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestAirportDistanceUnit', array($nearestAirportDistanceUnit));

        return parent::setNearestAirportDistanceUnit($nearestAirportDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestAirportDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestAirportDistanceUnit', array());

        return parent::getNearestAirportDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestBeach($nearestBeach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestBeach', array($nearestBeach));

        return parent::setNearestBeach($nearestBeach);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestBeach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestBeach', array());

        return parent::getNearestBeach();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestBeachDistance($nearestBeachDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestBeachDistance', array($nearestBeachDistance));

        return parent::setNearestBeachDistance($nearestBeachDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestBeachDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestBeachDistance', array());

        return parent::getNearestBeachDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestBeachDistanceUnit($nearestBeachDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestBeachDistanceUnit', array($nearestBeachDistanceUnit));

        return parent::setNearestBeachDistanceUnit($nearestBeachDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestBeachDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestBeachDistanceUnit', array());

        return parent::getNearestBeachDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestFerry($nearestFerry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestFerry', array($nearestFerry));

        return parent::setNearestFerry($nearestFerry);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestFerry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestFerry', array());

        return parent::getNearestFerry();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestFerryDistance($nearestFerryDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestFerryDistance', array($nearestFerryDistance));

        return parent::setNearestFerryDistance($nearestFerryDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestFerryDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestFerryDistance', array());

        return parent::getNearestFerryDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestFerryDistanceUnit($nearestFerryDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestFerryDistanceUnit', array($nearestFerryDistanceUnit));

        return parent::setNearestFerryDistanceUnit($nearestFerryDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestFerryDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestFerryDistanceUnit', array());

        return parent::getNearestFerryDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestTrain($nearestTrain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestTrain', array($nearestTrain));

        return parent::setNearestTrain($nearestTrain);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestTrain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestTrain', array());

        return parent::getNearestTrain();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestTrainDistance($nearestTrainDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestTrainDistance', array($nearestTrainDistance));

        return parent::setNearestTrainDistance($nearestTrainDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestTrainDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestTrainDistance', array());

        return parent::getNearestTrainDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestTrainDistanceUnit($nearestTrainDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestTrainDistanceUnit', array($nearestTrainDistanceUnit));

        return parent::setNearestTrainDistanceUnit($nearestTrainDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestTrainDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestTrainDistanceUnit', array());

        return parent::getNearestTrainDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestHighway($nearestHighway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestHighway', array($nearestHighway));

        return parent::setNearestHighway($nearestHighway);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestHighway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestHighway', array());

        return parent::getNearestHighway();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestHighwayDistance($nearestHighwayDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestHighwayDistance', array($nearestHighwayDistance));

        return parent::setNearestHighwayDistance($nearestHighwayDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestHighwayDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestHighwayDistance', array());

        return parent::getNearestHighwayDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestHighwayDistanceUnit($nearestHighwayDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestHighwayDistanceUnit', array($nearestHighwayDistanceUnit));

        return parent::setNearestHighwayDistanceUnit($nearestHighwayDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestHighwayDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestHighwayDistanceUnit', array());

        return parent::getNearestHighwayDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestBar($nearestBar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestBar', array($nearestBar));

        return parent::setNearestBar($nearestBar);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestBar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestBar', array());

        return parent::getNearestBar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestBarDistance($nearestBarDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestBarDistance', array($nearestBarDistance));

        return parent::setNearestBarDistance($nearestBarDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestBarDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestBarDistance', array());

        return parent::getNearestBarDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestBarDistanceUnit($nearestBarDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestBarDistanceUnit', array($nearestBarDistanceUnit));

        return parent::setNearestBarDistanceUnit($nearestBarDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestBarDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestBarDistanceUnit', array());

        return parent::getNearestBarDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestSki($nearestSki)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestSki', array($nearestSki));

        return parent::setNearestSki($nearestSki);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestSki()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestSki', array());

        return parent::getNearestSki();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestSkiDistance($nearestSkiDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestSkiDistance', array($nearestSkiDistance));

        return parent::setNearestSkiDistance($nearestSkiDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestSkiDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestSkiDistance', array());

        return parent::getNearestSkiDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestSkiDistanceUnit($nearestSkiDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestSkiDistanceUnit', array($nearestSkiDistanceUnit));

        return parent::setNearestSkiDistanceUnit($nearestSkiDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestSkiDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestSkiDistanceUnit', array());

        return parent::getNearestSkiDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestGolf($nearestGolf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestGolf', array($nearestGolf));

        return parent::setNearestGolf($nearestGolf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestGolf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestGolf', array());

        return parent::getNearestGolf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestGolfDistance($nearestGolfDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestGolfDistance', array($nearestGolfDistance));

        return parent::setNearestGolfDistance($nearestGolfDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestGolfDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestGolfDistance', array());

        return parent::getNearestGolfDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestGolfDistanceUnit($nearestGolfDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestGolfDistanceUnit', array($nearestGolfDistanceUnit));

        return parent::setNearestGolfDistanceUnit($nearestGolfDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestGolfDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestGolfDistanceUnit', array());

        return parent::getNearestGolfDistanceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestRestaurant($nearestRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestRestaurant', array($nearestRestaurant));

        return parent::setNearestRestaurant($nearestRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestRestaurant', array());

        return parent::getNearestRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestRestaurantDistance($nearestRestaurantDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestRestaurantDistance', array($nearestRestaurantDistance));

        return parent::setNearestRestaurantDistance($nearestRestaurantDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestRestaurantDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestRestaurantDistance', array());

        return parent::getNearestRestaurantDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNearestRestaurantDistanceUnit($nearestRestaurantDistanceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNearestRestaurantDistanceUnit', array($nearestRestaurantDistanceUnit));

        return parent::setNearestRestaurantDistanceUnit($nearestRestaurantDistanceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearestRestaurantDistanceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearestRestaurantDistanceUnit', array());

        return parent::getNearestRestaurantDistanceUnit();
    }

}
