<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Location extends \Frontend\AppBundle\Entity\Location implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'address', 'route', 'property_number', 'country', 'stateProvince', 'administrative_area_level_1', 'administrative_area_level_2', 'administrative_area_level_3', 'administrative_area_level_4', 'administrative_area_level_5', 'locality', 'sublocality', 'postal_town', 'neighborhood', 'postal_code', 'postal_code_prefix', 'public');
        }

        return array('__isInitialized__', 'id', 'address', 'route', 'property_number', 'country', 'stateProvince', 'administrative_area_level_1', 'administrative_area_level_2', 'administrative_area_level_3', 'administrative_area_level_4', 'administrative_area_level_5', 'locality', 'sublocality', 'postal_town', 'neighborhood', 'postal_code', 'postal_code_prefix', 'public');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Location $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic($Public)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', array($Public));

        return parent::setPublic($Public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', array());

        return parent::getPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoute($address2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoute', array($address2));

        return parent::setRoute($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoute', array());

        return parent::getRoute();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertyNumber($streetNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertyNumber', array($streetNumber));

        return parent::setPropertyNumber($streetNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropertyNumber', array());

        return parent::getPropertyNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setStateProvince($stateProvince)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStateProvince', array($stateProvince));

        return parent::setStateProvince($stateProvince);
    }

    /**
     * {@inheritDoc}
     */
    public function getStateProvince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateProvince', array());

        return parent::getStateProvince();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeAreaLevel1($stateCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeAreaLevel1', array($stateCode));

        return parent::setAdministrativeAreaLevel1($stateCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeAreaLevel1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeAreaLevel1', array());

        return parent::getAdministrativeAreaLevel1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeAreaLevel2($stateCode2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeAreaLevel2', array($stateCode2));

        return parent::setAdministrativeAreaLevel2($stateCode2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeAreaLevel2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeAreaLevel2', array());

        return parent::getAdministrativeAreaLevel2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeAreaLevel3($stateCode3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeAreaLevel3', array($stateCode3));

        return parent::setAdministrativeAreaLevel3($stateCode3);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeAreaLevel3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeAreaLevel3', array());

        return parent::getAdministrativeAreaLevel3();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeAreaLevel4($stateCode4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeAreaLevel4', array($stateCode4));

        return parent::setAdministrativeAreaLevel4($stateCode4);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeAreaLevel4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeAreaLevel4', array());

        return parent::getAdministrativeAreaLevel4();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeAreaLevel5($stateCode5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeAreaLevel5', array($stateCode5));

        return parent::setAdministrativeAreaLevel5($stateCode5);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeAreaLevel5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeAreaLevel5', array());

        return parent::getAdministrativeAreaLevel5();
    }

    /**
     * {@inheritDoc}
     */
    public function setSublocality($sublocality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSublocality', array($sublocality));

        return parent::setSublocality($sublocality);
    }

    /**
     * {@inheritDoc}
     */
    public function getSublocality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSublocality', array());

        return parent::getSublocality();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalTown($postalTown)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalTown', array($postalTown));

        return parent::setPostalTown($postalTown);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalTown()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalTown', array());

        return parent::getPostalTown();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeighborhood($neighborhood)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeighborhood', array($neighborhood));

        return parent::setNeighborhood($neighborhood);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeighborhood()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeighborhood', array());

        return parent::getNeighborhood();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCodePrefix($CodePrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCodePrefix', array($CodePrefix));

        return parent::setPostalCodePrefix($CodePrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCodePrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCodePrefix', array());

        return parent::getPostalCodePrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocality($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocality', array($city));

        return parent::setLocality($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocality', array());

        return parent::getLocality();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', array($zipCode));

        return parent::setPostalCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', array());

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
