<?php

namespace Proxies\__CG__\Frontend\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AttractionsAmenities extends \Frontend\AppBundle\Entity\AttractionsAmenities implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'barNightClub', 'beach', 'casino', 'charterBoats', 'deepSeaFishing', 'airports', 'horsebackRiding', 'shopping', 'snorkeling');
        }

        return array('__isInitialized__', 'id', 'barNightClub', 'beach', 'casino', 'charterBoats', 'deepSeaFishing', 'airports', 'horsebackRiding', 'shopping', 'snorkeling');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AttractionsAmenities $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarNightClub($barNightClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarNightClub', array($barNightClub));

        return parent::setBarNightClub($barNightClub);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarNightClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarNightClub', array());

        return parent::getBarNightClub();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeach($beach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeach', array($beach));

        return parent::setBeach($beach);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeach', array());

        return parent::getBeach();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasino($casino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasino', array($casino));

        return parent::setCasino($casino);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasino', array());

        return parent::getCasino();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharterBoats($charterBoats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharterBoats', array($charterBoats));

        return parent::setCharterBoats($charterBoats);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharterBoats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharterBoats', array());

        return parent::getCharterBoats();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeepSeaFishing($deepSeaFishing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeepSeaFishing', array($deepSeaFishing));

        return parent::setDeepSeaFishing($deepSeaFishing);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeepSeaFishing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeepSeaFishing', array());

        return parent::getDeepSeaFishing();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirports($airports)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirports', array($airports));

        return parent::setAirports($airports);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirports()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirports', array());

        return parent::getAirports();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorsebackRiding($horsebackRiding)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorsebackRiding', array($horsebackRiding));

        return parent::setHorsebackRiding($horsebackRiding);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorsebackRiding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorsebackRiding', array());

        return parent::getHorsebackRiding();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopping($shopping)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopping', array($shopping));

        return parent::setShopping($shopping);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopping()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopping', array());

        return parent::getShopping();
    }

    /**
     * {@inheritDoc}
     */
    public function setSnorkeling($snorkeling)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnorkeling', array($snorkeling));

        return parent::setSnorkeling($snorkeling);
    }

    /**
     * {@inheritDoc}
     */
    public function getSnorkeling()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnorkeling', array());

        return parent::getSnorkeling();
    }

}
